version: "3"
services:
  dashboard:
    container_name: dashboard
    image: 621771884374.dkr.ecr.us-west-2.amazonaws.com/dashboard
    restart: always
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options:
        awslogs-group: dashboard
        awslogs-region: eu-west-1
        awslogs-stream-prefix: dashboard
  mongo:
    container_name: mongo
    image: 621771884374.dkr.ecr.us-west-2.amazonaws.com/mongo
    ports:
      - "27017:27017"
  site:
    container_name: site
    image: 621771884374.dkr.ecr.us-west-2.amazonaws.com/site
    ports:
      - "3001:3001"