version: "3"
services:
  dashboard:
    container_name: dashboard
    build: ./dashboard
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  site:
    container_name: site
    build: ./site
    ports:
      - "3001:3001"